### ISSUE TITLE
[ISSUE] arreglar compilación de proyecto

### ISSUE THREAD

**Issue by equirosa** [DeimosPr4/katoikia-app#134]
Actualmente el proyecto en dev no logra compilar, mostrando este error:
```
Failed to compile.

./src/components/AdministradoresComunidad.js
  Line 354:9:  Parsing error: Identifier 'confirmDeleteSelected' has already been declared.

  352 |   };
  353 |
> 354 |   const confirmDeleteSelected = () => {
      |         ^
  355 |     setDeleteAdminsSystemDialog(true);
  356 |   };
  357 |
```

**Comment by equirosa** [comment]
como el profe nos acaba de decir que no borráramos realmente, no sé si esta función sea totalmente necesaria. De todos modos voy a ver en qué commit es que deja de funcionar

**Comment by Mariela34** [comment]
errores de compilación arreglos en branch de registrar admin de comunidad... en proceso de PR
